name: Update Events

on:
  push:
    paths:
      - events.json   # triggers only when events.json changes

jobs:
  process-events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read events
        run: |
          echo "Events JSON:"
          cat events.json
      # Add your processing steps here
